/**
 * Deterministic font delivery. The faces the source page actually rendered are downloaded into the
 * frontend's resources and declared in a generated `_fonts.scss`, so no agent has to find, fetch or
 * reference a font file: in real runs that step left every source face rendering from a fallback.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

export const FONTS_DIR = 'ui.frontend/src/main/webpack/resources/fonts';
export const FONTS_SCSS = 'ui.frontend/src/main/webpack/site/_fonts.scss';
export const MAIN_SCSS = 'ui.frontend/src/main/webpack/site/main.scss';
// Files this module owns; anything else in the fonts folder belongs to someone else and stays.
const GENERATED_PREFIX = 'src-';
// Compiled CSS is served from clientlib-site/css/ and AEM resolves url() against that folder.
const URL_PREFIX = '../resources/fonts/';

const FORMAT_RANK = { woff2: 0, woff: 1, opentype: 2, truetype: 3 };
const EXTENSION_BY_FORMAT = {
  woff2: 'woff2', woff: 'woff', opentype: 'otf', truetype: 'ttf', 'embedded-opentype': 'eot',
};
const EXTENSION_BY_MIME = {
  'font/woff2': 'woff2', 'font/woff': 'woff', 'font/ttf': 'ttf', 'font/otf': 'otf', 'application/font-woff': 'woff',
};

const slug = (value) => String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'x';
const digestOf = (value) => crypto.createHash('sha1').update(value).digest('hex').slice(0, 8);

function extensionOf(source, mime) {
  if (source.format && EXTENSION_BY_FORMAT[source.format]) return EXTENSION_BY_FORMAT[source.format];
  if (mime && EXTENSION_BY_MIME[mime]) return EXTENSION_BY_MIME[mime];
  const fromUrl = /\.([a-z0-9]{2,5})(?:$|[?#])/i.exec(source.url.startsWith('data:') ? '' : source.url)?.[1]?.toLowerCase();
  return fromUrl && ['woff2', 'woff', 'ttf', 'otf', 'eot'].includes(fromUrl) ? fromUrl : 'woff2';
}

/** The faces the source rendered. A rule nobody used would only add weight to the page. */
export function usedFaces(discovery) {
  return (discovery?.fonts?.faces || []).filter((face) => face.loaded && face.src?.length);
}

export function bestSource(face) {
  const rank = (entry) => FORMAT_RANK[entry.format] ?? (/\.woff2(?:$|[?#])/i.test(entry.url) ? 0 : 4);
  return [...face.src].sort((left, right) => rank(left) - rank(right))[0];
}

const quoteFamily = (family) => `"${String(family).replace(/"/g, '\\"')}"`;

export function fontFaceScss(entries) {
  const lines = [
    '// Generated by the migration orchestrator from the source page\'s @font-face rules; every run',
    '// rewrites it. Declare font families in tokens against these names, never another @font-face.',
  ];
  for (const entry of entries) {
    lines.push('', '@font-face {');
    lines.push(`    font-family: ${quoteFamily(entry.family)};`);
    lines.push(`    src: url("${URL_PREFIX}${entry.file}") format("${entry.format}");`);
    lines.push(`    font-weight: ${entry.weight};`);
    lines.push(`    font-style: ${entry.style};`);
    if (entry.stretch && entry.stretch !== 'normal') lines.push(`    font-stretch: ${entry.stretch};`);
    if (entry.unicode_range) lines.push(`    unicode-range: ${entry.unicode_range};`);
    if (entry.display) lines.push(`    font-display: ${entry.display};`);
    lines.push('}');
  }
  return `${lines.join('\n')}\n`;
}

/** `_fonts.scss` is imported right after the tokens, whatever else main.scss imports. */
export function ensureFontsImport(repoRoot) {
  const absolute = path.join(repoRoot, MAIN_SCSS);
  if (!fs.existsSync(absolute)) return false;
  const text = fs.readFileSync(absolute, 'utf8');
  if (/@(import|use)\s+['"](\.\/)?_?fonts['"]/.test(text)) return false;
  const eol = text.includes('\r\n') ? '\r\n' : '\n';
  const lines = text.split(/\r?\n/);
  const tokens = lines.findIndex((line) => /@(import|use)\s+['"](\.\/)?_?tokens['"]/.test(line));
  lines.splice(tokens >= 0 ? tokens + 1 : 0, 0, "@import 'fonts';");
  fs.writeFileSync(absolute, lines.join(eol), 'utf8');
  return true;
}

/** (Re)writes the generated partial and its import; the orchestrator owns both. */
export function writeFontsScss(repoRoot, entries) {
  if (!fs.existsSync(path.join(repoRoot, MAIN_SCSS))) return [];
  const scssPath = path.join(repoRoot, FONTS_SCSS);
  fs.mkdirSync(path.dirname(scssPath), { recursive: true });
  fs.writeFileSync(scssPath, fontFaceScss(entries), 'utf8');
  return [FONTS_SCSS, ...(ensureFontsImport(repoRoot) ? [MAIN_SCSS] : [])];
}

/**
 * Downloads every used face into the frontend resources and writes `_fonts.scss`. A face that cannot
 * be fetched is reported, not fatal: the rest still ship, and parity names what still falls back.
 */
export async function acquireFonts({
  repoRoot, discovery, fetchFn = fetch, referer,
}) {
  const faces = usedFaces(discovery);
  const fontsDir = path.join(repoRoot, FONTS_DIR);
  if (fs.existsSync(fontsDir)) {
    for (const name of fs.readdirSync(fontsDir)) {
      if (name.startsWith(GENERATED_PREFIX)) fs.rmSync(path.join(fontsDir, name), { force: true });
    }
  }
  if (!faces.length) {
    // main.scss may already import it from an earlier run, so the partial stays, empty.
    const written = writeFontsScss(repoRoot, []);
    return {
      status: 'SKIPPED', faces: [], families: [], failures: [], written,
    };
  }

  fs.mkdirSync(fontsDir, { recursive: true });
  const downloaded = new Map();
  const entries = [];
  const failures = [];
  const written = [];
  for (const face of faces) {
    const source = bestSource(face);
    let file = downloaded.get(source.url);
    if (!file) {
      try {
        const response = await fetchFn(source.url, { redirect: 'follow', headers: referer ? { referer } : {} });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const bytes = Buffer.from(await response.arrayBuffer());
        if (!bytes.length) throw new Error('empty response body');
        const mime = String(response.headers?.get?.('content-type') || '').split(';')[0].trim().toLowerCase();
        file = `${GENERATED_PREFIX}${slug(face.family)}-${slug(face.weight)}-${slug(face.style)}-${digestOf(source.url)}`
          + `.${extensionOf(source, mime)}`;
        fs.writeFileSync(path.join(fontsDir, file), bytes);
        written.push(`${FONTS_DIR}/${file}`);
        downloaded.set(source.url, file);
      } catch (error) {
        failures.push({ family: face.family, weight: face.weight, style: face.style, url: source.url, reason: error.message });
        continue;
      }
    }
    entries.push({
      family: face.family,
      weight: face.weight,
      style: face.style,
      stretch: face.stretch,
      unicode_range: face.unicode_range,
      display: face.display,
      format: source.format || extensionOf(source).replace('ttf', 'truetype').replace('otf', 'opentype'),
      file,
      url: source.url,
    });
  }

  entries.sort((left, right) => `${left.family}|${left.weight}|${left.style}|${left.unicode_range || ''}`
    .localeCompare(`${right.family}|${right.weight}|${right.style}|${right.unicode_range || ''}`));
  written.push(...writeFontsScss(repoRoot, entries));
  return {
    status: failures.length ? 'PARTIAL' : 'PASS',
    faces: entries,
    families: [...new Set(entries.map((entry) => entry.family))],
    failures,
    written,
  };
}
