/**
 * Early visual feedback. Each merged component is deployed with everything merged before it and
 * scored against the live source on its own, while its worker's session and workspace still exist,
 * instead of every component being judged for the first time after the whole fan-out.
 *
 * All AEM work is serialized through one queue. Any infrastructure failure disables previews for
 * the rest of the run and the fan-out carries on exactly as it would without them.
 */
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import { applyContributions } from './contributions.mjs';
import { planDeployment, runDeployment } from './deploy.mjs';
import { parityComponents } from './plan.mjs';
import { syncWorkspace, snapshotTree } from './workspaces.mjs';

const DEFAULT_CONTENT_ROOT = 'ui.content/src/main/content/jcr_root';
// What the frontend build writes into ui.apps; regenerated by every deploy, never edited by hand.
const BUILD_OUTPUT = /^ui\.apps\/src\/main\/content\/jcr_root\/apps\/[^/]+\/clientlibs\/clientlib-(site|dependencies)\//;

const CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let index = 0; index < 256; index += 1) {
    let value = index;
    for (let bit = 0; bit < 8; bit += 1) value = value & 1 ? 0xEDB88320 ^ (value >>> 1) : value >>> 1;
    table[index] = value >>> 0;
  }
  return table;
})();

export function crc32(bytes) {
  let crc = 0xFFFFFFFF;
  for (const byte of bytes) crc = CRC_TABLE[(crc ^ byte) & 0xFF] ^ (crc >>> 8);
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

/** A stored (uncompressed) zip: Package Manager needs a valid archive, not a small one. */
export function createZip(entries) {
  const locals = [];
  const centrals = [];
  let offset = 0;
  // 1980-01-01 00:00, the first date the format can hold, so output is byte-stable.
  const dosDate = (0 << 9) | (1 << 5) | 1;
  for (const entry of entries) {
    const name = Buffer.from(entry.name.replaceAll('\\', '/'), 'utf8');
    const data = Buffer.isBuffer(entry.data) ? entry.data : Buffer.from(entry.data, 'utf8');
    const crc = crc32(data);
    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(0x0800, 6);
    local.writeUInt16LE(0, 8);
    local.writeUInt16LE(0, 10);
    local.writeUInt16LE(dosDate, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(data.length, 18);
    local.writeUInt32LE(data.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28);
    locals.push(local, name, data);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(0x0800, 8);
    central.writeUInt16LE(0, 10);
    central.writeUInt16LE(0, 12);
    central.writeUInt16LE(dosDate, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(data.length, 20);
    central.writeUInt32LE(data.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, name);
    offset += local.length + name.length + data.length;
  }
  const directory = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(directory.length, 12);
  end.writeUInt32LE(offset, 16);
  return Buffer.concat([...locals, directory, end]);
}

const escapeXml = (value) => String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

/**
 * A content package holding exactly the composed documents: each one is its own replace-mode root,
 * so installing it never touches anything else in the repository.
 */
export function buildContentPackage({
  root, files, name, version, contentRoot = DEFAULT_CONTENT_ROOT,
}) {
  const entries = [];
  const roots = [];
  for (const file of files) {
    const relative = file.replaceAll('\\', '/');
    if (!relative.startsWith(`${contentRoot}/`) || !relative.endsWith('/.content.xml')) continue;
    const jcrPath = `/${relative.slice(contentRoot.length + 1, -'/.content.xml'.length)}`;
    roots.push(jcrPath);
    entries.push({ name: `jcr_root${jcrPath}/.content.xml`, data: fs.readFileSync(path.join(root, relative)) });
  }
  if (!roots.length) return null;
  const filter = ['<?xml version="1.0" encoding="UTF-8"?>', '<workspaceFilter version="1.0">',
    ...roots.map((jcrPath) => `    <filter root="${escapeXml(jcrPath)}"/>`), '</workspaceFilter>', ''].join('\n');
  const properties = ['<?xml version="1.0" encoding="UTF-8" standalone="no"?>',
    '<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">', '<properties>',
    '<entry key="group">migration-preview</entry>', `<entry key="name">${escapeXml(name)}</entry>`,
    `<entry key="version">${escapeXml(version)}</entry>`, '</properties>', ''].join('\n');
  return {
    roots,
    zip: createZip([
      { name: 'META-INF/vault/filter.xml', data: filter },
      { name: 'META-INF/vault/properties.xml', data: properties },
      ...entries,
    ]),
  };
}

export async function installPackage({
  aemUrl, username, password, zip, name, fetchFn = fetch,
}) {
  const form = new FormData();
  form.append('file', new Blob([zip], { type: 'application/zip' }), `${name}.zip`);
  form.append('name', name);
  form.append('force', 'true');
  form.append('install', 'true');
  try {
    const response = await fetchFn(`${aemUrl}/crx/packmgr/service.jsp`, {
      method: 'POST',
      headers: { authorization: `Basic ${Buffer.from(`${username}:${password ?? ''}`).toString('base64')}` },
      body: form,
    });
    const text = await response.text();
    const ok = response.ok && /<status code="200">/.test(text);
    return { ok, status: response.status, detail: ok ? null : text.slice(-500) };
  } catch (error) {
    return { ok: false, status: null, detail: error.message };
  }
}

/** A mutex whose `run` queues work behind whatever holds it. */
function createQueue() {
  let tail = Promise.resolve();
  return {
    run(task) {
      const next = tail.then(task, task);
      tail = next.catch(() => {});
      return next;
    },
  };
}

export function createPreview({
  repoRoot, evidenceDir, plan, discovery, options, execFn, fetchFn, runTool, renderer, treeLock,
  instanceOrder, workspaceOptions, toolsDir, guard = null, beforeFirstDeploy = null,
}) {
  const queue = createQueue();
  const previewRoot = path.join(evidenceDir, 'workspaces', '_preview');
  const aemUrl = `http://${options.aemHost}:${options.aemPort}`;
  const targetUrl = `${aemUrl}${options.targetPath}.html?wcmmode=disabled`;
  const state = { disabled: null, ready: false, installs: 0 };

  const disable = (reason) => {
    if (state.disabled) return;
    state.disabled = reason;
    renderer.warn(`previews disabled for the rest of the run: ${reason}`);
  };

  /** One full deploy from the tree, so the DAM, template, tokens and fonts are on the instance. */
  async function prepare() {
    if (beforeFirstDeploy) await beforeFirstDeploy();
    const release = await treeLock.acquire();
    const before = guard ? snapshotTree(repoRoot, workspaceOptions) : null;
    try {
      const deployment = await runDeployment({
        repoRoot,
        steps: planDeployment(options.aemPort),
        renderer,
        execFn,
        logPath: path.join(evidenceDir, 'preview', 'deploy.log'),
        writeLog: (file, text) => {
          fs.mkdirSync(path.dirname(file), { recursive: true });
          fs.appendFileSync(file, text);
        },
      });
      if (deployment.status !== 'PASS') {
        disable(`the first deploy failed at ${deployment.failure.step} (exit ${deployment.failure.exit_code})`);
        return;
      }
      state.ready = true;
    } finally {
      if (guard) {
        // The build rewrote its own output in the tree; that is not someone editing alongside the run.
        const after = snapshotTree(repoRoot, workspaceOptions);
        guard.record([...new Set([...before.keys(), ...after.keys()])]
          .filter((file) => before.get(file) !== after.get(file) && BUILD_OUTPUT.test(file)));
      }
      release();
    }
  }

  async function measure({ component, results, round }) {
    if (!state.ready) await prepare();
    if (state.disabled) return { skipped: state.disabled };

    const release = await treeLock.acquire();
    try {
      syncWorkspace(repoRoot, previewRoot, workspaceOptions);
    } finally {
      release();
    }
    const composed = applyContributions({
      repoRoot: previewRoot, plan, results, instanceOrder, receipt: {},
    });
    if (composed.conflicts.length) return { skipped: `compose conflict: ${composed.conflicts[0].kind}` };

    const label = `${component.id}-${round}`;
    const outDir = path.join(evidenceDir, 'preview', label);
    fs.mkdirSync(outDir, { recursive: true });
    const build = await runDeployment({
      repoRoot: previewRoot,
      steps: [{
        label: `preview build and install (${component.id})`,
        module: 'core,ui.apps',
        command: 'mvn',
        args: ['install', '-pl', 'core,ui.apps', '-PautoInstallPackage,autoInstallBundle', `-Daem.port=${options.aemPort}`,
          `-Daem.host=${options.aemHost}`, '-DskipTests'],
      }],
      renderer,
      execFn,
      logPath: path.join(outDir, 'deploy.log'),
      writeLog: fs.appendFileSync,
    });
    if (build.status !== 'PASS') {
      if (build.failure.kind === 'environment') disable(`the preview build hit an environment fault (${build.failure.step})`);
      return { skipped: `preview build failed (${build.failure.step})` };
    }

    const content = buildContentPackage({
      root: previewRoot,
      files: composed.written.map((file) => path.relative(previewRoot, file)),
      name: 'preview',
      version: String(state.installs += 1),
      contentRoot: plan.shared?.content_root || DEFAULT_CONTENT_ROOT,
    });
    if (content) {
      const installed = await installPackage({
        aemUrl,
        username: options.aemUser || 'admin',
        password: process.env.AEM_PASSWORD,
        zip: content.zip,
        name: 'preview',
        fetchFn,
      });
      if (!installed.ok) {
        disable(`Package Manager refused the preview content (${installed.status ?? 'no response'})`);
        return { skipped: state.disabled };
      }
    }

    const components = parityComponents(plan, discovery, options.breakpoints)
      .filter((entry) => entry.id === component.id);
    if (!components.length) return { skipped: 'no parity target for this component' };
    const configPath = path.join(outDir, 'parity-config.json');
    fs.writeFileSync(configPath, `${JSON.stringify({
      run_id: `${path.basename(evidenceDir)}-preview`,
      source_url: discovery.source.final_url,
      targets: [{ mode: 'preview', url: targetUrl }],
      breakpoints: options.breakpoints,
      threshold: options.threshold,
      auth: { username: options.aemUser || 'admin', password_env: 'AEM_PASSWORD' },
      composite: false,
      components,
    }, null, 2)}\n`, 'utf8');
    await runTool('parity', [path.join(toolsDir, 'parity.mjs'), '--config', configPath, '--out', outDir, '--cycle', String(round)]);
    const artefactPath = path.join(outDir, 'parity.json');
    if (!fs.existsSync(artefactPath)) return { skipped: 'the preview parity run produced no artefact' };
    const parity = JSON.parse(fs.readFileSync(artefactPath, 'utf8'));
    if (parity.preflight?.environment_blocked) {
      disable('the preview page could not be reached');
      return { skipped: state.disabled };
    }
    const summary = (parity.components || []).find((entry) => entry.component_id === component.id);
    return {
      status: summary?.status || 'FAIL', summary, parity, outDir,
    };
  }

  return {
    get disabled() { return state.disabled; },
    /** Serialized: one component at a time owns the instance. */
    check(request) {
      if (state.disabled) return Promise.resolve({ skipped: state.disabled });
      return queue.run(() => measure(request).catch((error) => {
        disable(error.message);
        return { skipped: state.disabled };
      }));
    },
  };
}
