/**
 * Worker isolation. Each component agent runs in its own copy of the repository so
 * concurrent workers cannot collide, and every change it produces is checked against the
 * paths the plan gave it before anything is merged back.
 */
import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

// Build output and vendored toolchains. `node` is where the frontend-maven-plugin drops a
// private node runtime; it is regenerated by the build, never edited by a worker. `.migration`
// holds the inputs the orchestrator wrote for the worker, which are not the worker's output.
const EXCLUDED_DIRECTORIES = new Set([
  'node_modules', 'target', '.git', 'dist', 'build', '.autofix', 'coverage', '.vlt', 'node', '.migration',
]);

/** Evidence lives outside the worktree so workers cannot read or corrupt other workers' runs. */
const EXCLUDED_RELATIVE = new Set(['design/scratch']);

/**
 * The DAM tree is never owned by a component worker and holds the repository's large binaries,
 * so excluding it by path is what keeps a fan-out cheap. Projects with a different layout can
 * override this. Size is deliberately not a criterion: a legitimate 100 MB video lives here.
 */
export const DEFAULT_EXCLUDE_PATTERNS = [/(^|\/)jcr_root\/content\/dam\//];

/** Opt-in only. Zero disables the cap so no owned file is ever silently withheld. */
export const DEFAULT_MAX_FILE_BYTES = 0;

function normalize(value) {
  return String(value).replaceAll('\\', '/').replace(/^\.\//, '').replace(/\/+$/, '');
}

function buildFilter(options = {}) {
  const patterns = options.excludePatterns || DEFAULT_EXCLUDE_PATTERNS;
  const maxBytes = options.maxFileBytes ?? DEFAULT_MAX_FILE_BYTES;
  const directories = options.excludeDirectories
    ? new Set([...EXCLUDED_DIRECTORIES, ...options.excludeDirectories])
    : EXCLUDED_DIRECTORIES;

  return {
    skipEntry(relativePath, name, isDirectory) {
      if (directories.has(name)) return true;
      const normalized = normalize(relativePath);
      if (EXCLUDED_RELATIVE.has(normalized)) return true;
      // A directory is tested with a trailing slash so a prefix pattern excludes the folder itself.
      const candidate = isDirectory ? `${normalized}/` : normalized;
      return patterns.some((pattern) => pattern.test(candidate));
    },
    skipFile(absolutePath) {
      if (!Number.isFinite(maxBytes) || maxBytes <= 0) return false;
      try {
        return fs.statSync(absolutePath).size > maxBytes;
      } catch {
        return false;
      }
    },
  };
}

function hashFile(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

export function snapshotTree(root, options = {}) {
  const filter = buildFilter(options);
  const files = new Map();
  const walk = (directory, relative) => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const childRelative = relative ? `${relative}/${entry.name}` : entry.name;
      if (filter.skipEntry(childRelative, entry.name, entry.isDirectory())) continue;
      const childPath = path.join(directory, entry.name);
      if (entry.isDirectory()) walk(childPath, childRelative);
      else if (entry.isFile() && !filter.skipFile(childPath)) files.set(childRelative, hashFile(childPath));
    }
  };
  walk(root, '');
  return files;
}

export function createWorkspace(repoRoot, workspaceRoot, options = {}) {
  const filter = buildFilter(options);
  // A killed attempt never runs its cleanup, so never copy into whatever it left behind.
  fs.rmSync(workspaceRoot, { recursive: true, force: true });
  fs.mkdirSync(workspaceRoot, { recursive: true });
  const copy = (source, destination, relative) => {
    for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
      const childRelative = relative ? `${relative}/${entry.name}` : entry.name;
      if (filter.skipEntry(childRelative, entry.name, entry.isDirectory())) continue;
      const from = path.join(source, entry.name);
      const to = path.join(destination, entry.name);
      if (entry.isDirectory()) {
        fs.mkdirSync(to, { recursive: true });
        copy(from, to, childRelative);
      } else if (entry.isFile() && !filter.skipFile(from)) {
        fs.copyFileSync(from, to);
      }
    }
  };
  copy(repoRoot, workspaceRoot, '');
  const git = options.git === false ? false : initGit(workspaceRoot);
  return {
    root: workspaceRoot, options, baseline: snapshotTree(workspaceRoot, options), git,
  };
}

/**
 * A copy without `.git` sits inside the real repository, so git in it walked up and acted on the
 * user's working tree. Its own repository, committed at the baseline, also shows the worker its diff.
 */
function initGit(root) {
  const run = (args) => spawnSync('git', args, {
    cwd: root,
    stdio: 'ignore',
    windowsHide: true,
    env: { ...process.env, GIT_CEILING_DIRECTORIES: path.dirname(root) },
  });
  try {
    if (run(['init', '-q']).status !== 0) return false;
    run(['-c', 'core.autocrlf=false', '-c', 'core.safecrlf=false', 'add', '-A']);
    return run(['-c', 'user.name=migration', '-c', 'user.email=migration@localhost', '-c', 'commit.gpgsign=false',
      'commit', '-q', '--no-verify', '-m', 'baseline']).status === 0;
  } catch {
    return false;
  }
}

/**
 * Brings a long-lived copy up to date with the repository while keeping its build output, so a
 * Maven build in it stays incremental. Returns the files it copied and deleted.
 */
export function syncWorkspace(repoRoot, workspaceRoot, options = {}) {
  const filter = buildFilter(options);
  const copied = [];
  const deleted = [];
  const seen = new Set();
  const walk = (relative) => {
    for (const entry of fs.readdirSync(path.join(repoRoot, relative), { withFileTypes: true })) {
      const child = relative ? `${relative}/${entry.name}` : entry.name;
      if (filter.skipEntry(child, entry.name, entry.isDirectory())) continue;
      if (entry.isDirectory()) {
        walk(child);
        continue;
      }
      if (!entry.isFile()) continue;
      seen.add(child);
      const from = path.join(repoRoot, child);
      const to = path.join(workspaceRoot, child);
      if (fs.existsSync(to) && hashFile(to) === hashFile(from)) continue;
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
      copied.push(child);
    }
  };
  fs.mkdirSync(workspaceRoot, { recursive: true });
  walk('');
  for (const relative of snapshotTree(workspaceRoot, options).keys()) {
    if (seen.has(relative)) continue;
    fs.rmSync(path.join(workspaceRoot, relative), { force: true });
    deleted.push(relative);
  }
  return { copied, deleted };
}

function ownsPath(ownedPaths, candidate) {
  const target = normalize(candidate);
  return ownedPaths.some((owned) => {
    const scope = normalize(owned);
    if (scope.endsWith('/**')) return target.startsWith(`${scope.slice(0, -3)}/`);
    return target === scope || target.startsWith(`${scope}/`);
  });
}

/** Compares a finished worker against its baseline and rejects anything outside its scope. */
export function collectChanges(workspace, ownedPaths) {
  const current = snapshotTree(workspace.root, workspace.options || {});
  const added = [];
  const modified = [];
  const deleted = [];

  for (const [relative, hash] of current) {
    const before = workspace.baseline.get(relative);
    if (before === undefined) added.push(relative);
    else if (before !== hash) modified.push(relative);
  }
  for (const relative of workspace.baseline.keys()) {
    if (!current.has(relative)) deleted.push(relative);
  }

  const changed = [...added, ...modified, ...deleted];
  const violations = changed.filter((relative) => !ownsPath(ownedPaths, relative));
  // Everything the worker owns that exists now; a rebuild can leave a file byte-identical.
  const owned = [...current.keys()].filter((relative) => ownsPath(ownedPaths, relative));
  return {
    added, modified, deleted, changed, owned, violations, valid: violations.length === 0,
  };
}

/** The reactor's modules and root POM: what a deploy builds, so the only edits that can ship. */
function reactorRoots(repoRoot) {
  let pom;
  try {
    pom = fs.readFileSync(path.join(repoRoot, 'pom.xml'), 'utf8');
  } catch {
    return null;
  }
  const modules = [...pom.matchAll(/<module>\s*([^<]+?)\s*<\/module>/g)].map((match) => normalize(match[1]));
  return modules.length ? ['pom.xml', ...modules] : null;
}

/** The tree as the run last left it; a change no merge made is someone editing alongside the workers. */
export function watchTree(repoRoot, options = {}) {
  const roots = reactorRoots(repoRoot);
  const deployable = (relative) => !roots || roots.some((root) => relative === root || relative.startsWith(`${root}/`));
  const expected = snapshotTree(repoRoot, options);
  const hashAt = (relative) => {
    const file = path.join(repoRoot, relative);
    return fs.existsSync(file) ? hashFile(file) : undefined;
  };
  return {
    /** Those of `files` that changed since the run last saw them. */
    touched: (files) => files.map(normalize).filter((relative) => hashAt(relative) !== expected.get(relative)),
    record(files) {
      for (const relative of files.map(normalize)) {
        const hash = hashAt(relative);
        if (hash === undefined) expected.delete(relative);
        else expected.set(relative, hash);
      }
    },
    /** Every deployable file that differs from what the run expects, however it changed. */
    drift() {
      const current = snapshotTree(repoRoot, options);
      return [...new Set([...expected.keys(), ...current.keys()])]
        .filter((relative) => deployable(relative) && current.get(relative) !== expected.get(relative))
        .sort();
    },
  };
}

/**
 * Applies an accepted worker's changes to the shared tree; conflicts are refused, not merged.
 * Given a guard, a file edited in the shared tree since the run last saw it is refused as well.
 */
export function mergeChanges(workspace, repoRoot, changes, claimedPaths, guard = null) {
  const conflicts = [];
  for (const relative of changes.changed) {
    const owner = claimedPaths.get(normalize(relative));
    if (owner && owner !== workspace.id) conflicts.push({ path: relative, owner });
  }
  if (conflicts.length) return { applied: [], conflicts, edited: [] };
  const edited = guard ? guard.touched(changes.changed) : [];
  if (edited.length) return { applied: [], conflicts: [], edited };

  const applied = [];
  for (const relative of [...changes.added, ...changes.modified]) {
    const from = path.join(workspace.root, relative);
    const to = path.join(repoRoot, relative);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    claimedPaths.set(normalize(relative), workspace.id);
    applied.push(relative);
  }
  for (const relative of changes.deleted) {
    const to = path.join(repoRoot, relative);
    if (fs.existsSync(to)) fs.rmSync(to);
    claimedPaths.set(normalize(relative), workspace.id);
    applied.push(relative);
  }
  guard?.record(applied);
  return { applied, conflicts: [], edited: [] };
}

export function removeWorkspace(workspaceRoot) {
  fs.rmSync(workspaceRoot, { recursive: true, force: true });
}
