/**
 * Worker isolation. Each component agent runs in its own copy of the repository so
 * concurrent workers cannot collide, and every change it produces is checked against the
 * paths the plan gave it before anything is merged back.
 */
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

// Build output and vendored toolchains. `node` is where the frontend-maven-plugin drops a
// private node runtime; it is regenerated by the build, never edited by a worker.
const EXCLUDED_DIRECTORIES = new Set([
  'node_modules', 'target', '.git', 'dist', 'build', '.autofix', 'coverage', '.vlt', 'node',
]);

/** Evidence lives outside the worktree so workers cannot read or corrupt other workers' runs. */
const EXCLUDED_RELATIVE = new Set(['design/scratch']);

/**
 * The DAM tree is never owned by a component worker and holds the repository's large binaries,
 * so excluding it by path is what keeps a fan-out cheap. Projects with a different layout can
 * override this. Size is deliberately not a criterion: a legitimate 100 MB video lives here.
 */
export const DEFAULT_EXCLUDE_PATTERNS = [/(^|\/)jcr_root\/content\/dam\//];

/** Opt-in only. Zero disables the cap so no owned file is ever silently withheld. */
export const DEFAULT_MAX_FILE_BYTES = 0;

function normalize(value) {
  return String(value).replaceAll('\\', '/').replace(/^\.\//, '').replace(/\/+$/, '');
}

function buildFilter(options = {}) {
  const patterns = options.excludePatterns || DEFAULT_EXCLUDE_PATTERNS;
  const maxBytes = options.maxFileBytes ?? DEFAULT_MAX_FILE_BYTES;
  const directories = options.excludeDirectories
    ? new Set([...EXCLUDED_DIRECTORIES, ...options.excludeDirectories])
    : EXCLUDED_DIRECTORIES;

  return {
    skipEntry(relativePath, name, isDirectory) {
      if (directories.has(name)) return true;
      const normalized = normalize(relativePath);
      if (EXCLUDED_RELATIVE.has(normalized)) return true;
      // A directory is tested with a trailing slash so a prefix pattern excludes the folder itself.
      const candidate = isDirectory ? `${normalized}/` : normalized;
      return patterns.some((pattern) => pattern.test(candidate));
    },
    skipFile(absolutePath) {
      if (!Number.isFinite(maxBytes) || maxBytes <= 0) return false;
      try {
        return fs.statSync(absolutePath).size > maxBytes;
      } catch {
        return false;
      }
    },
  };
}

function hashFile(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

export function snapshotTree(root, options = {}) {
  const filter = buildFilter(options);
  const files = new Map();
  const walk = (directory, relative) => {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
      const childRelative = relative ? `${relative}/${entry.name}` : entry.name;
      if (filter.skipEntry(childRelative, entry.name, entry.isDirectory())) continue;
      const childPath = path.join(directory, entry.name);
      if (entry.isDirectory()) walk(childPath, childRelative);
      else if (entry.isFile() && !filter.skipFile(childPath)) files.set(childRelative, hashFile(childPath));
    }
  };
  walk(root, '');
  return files;
}

export function createWorkspace(repoRoot, workspaceRoot, options = {}) {
  const filter = buildFilter(options);
  fs.mkdirSync(workspaceRoot, { recursive: true });
  const copy = (source, destination, relative) => {
    for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
      const childRelative = relative ? `${relative}/${entry.name}` : entry.name;
      if (filter.skipEntry(childRelative, entry.name, entry.isDirectory())) continue;
      const from = path.join(source, entry.name);
      const to = path.join(destination, entry.name);
      if (entry.isDirectory()) {
        fs.mkdirSync(to, { recursive: true });
        copy(from, to, childRelative);
      } else if (entry.isFile() && !filter.skipFile(from)) {
        fs.copyFileSync(from, to);
      }
    }
  };
  copy(repoRoot, workspaceRoot, '');
  return { root: workspaceRoot, options, baseline: snapshotTree(workspaceRoot, options) };
}

function ownsPath(ownedPaths, candidate) {
  const target = normalize(candidate);
  return ownedPaths.some((owned) => {
    const scope = normalize(owned);
    if (scope.endsWith('/**')) return target.startsWith(`${scope.slice(0, -3)}/`);
    return target === scope || target.startsWith(`${scope}/`);
  });
}

/** Compares a finished worker against its baseline and rejects anything outside its scope. */
export function collectChanges(workspace, ownedPaths) {
  const current = snapshotTree(workspace.root, workspace.options || {});
  const added = [];
  const modified = [];
  const deleted = [];

  for (const [relative, hash] of current) {
    const before = workspace.baseline.get(relative);
    if (before === undefined) added.push(relative);
    else if (before !== hash) modified.push(relative);
  }
  for (const relative of workspace.baseline.keys()) {
    if (!current.has(relative)) deleted.push(relative);
  }

  const changed = [...added, ...modified, ...deleted];
  const violations = changed.filter((relative) => !ownsPath(ownedPaths, relative));
  return {
    added, modified, deleted, changed, violations, valid: violations.length === 0,
  };
}

/** Applies an accepted worker's changes to the shared tree; conflicts are refused, not merged. */
export function mergeChanges(workspace, repoRoot, changes, claimedPaths) {
  const conflicts = [];
  for (const relative of changes.changed) {
    const owner = claimedPaths.get(normalize(relative));
    if (owner && owner !== workspace.id) conflicts.push({ path: relative, owner });
  }
  if (conflicts.length) return { applied: [], conflicts };

  const applied = [];
  for (const relative of [...changes.added, ...changes.modified]) {
    const from = path.join(workspace.root, relative);
    const to = path.join(repoRoot, relative);
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
    claimedPaths.set(normalize(relative), workspace.id);
    applied.push(relative);
  }
  for (const relative of changes.deleted) {
    const to = path.join(repoRoot, relative);
    if (fs.existsSync(to)) fs.rmSync(to);
    claimedPaths.set(normalize(relative), workspace.id);
    applied.push(relative);
  }
  return { applied, conflicts: [] };
}

export function removeWorkspace(workspaceRoot) {
  fs.rmSync(workspaceRoot, { recursive: true, force: true });
}
