$env:JAVA_HOME = "C:\Program Files\Zulu\zulu-26"
$env:PATH = "$env:JAVA_HOME\bin;$env:PATH"
Set-Location "C:\projects\Trainings\new\demo-ai-site"
$log = "design\scratch\migration-028116ff-77cc-4698-b546-02e75bf80757\stage2\core-compile.log"
cmd /c "mvn.cmd -pl core compile -o > $log 2>&1"
Select-String -Path $log -Pattern "BUILD SUCCESS|BUILD FAILURE|ERROR"
